on: ["push", "pull_request"]

name: Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    - name: npm install, npm run test and send coverage to Coveralls
      run: |
        npm install
        npm run test

    - name: Coveralls
      uses: coverallsapp/github-action@v2